list(
  APPEND
  LV_EDITOR_PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/components/bottom_key_bar/bottom_key_bar_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/top_status_bar/top_status_bar_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_cn_12_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_cn_14_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_cn_16_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_cn_18_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_cn_20_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_cn_24_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_cn_34_data.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_alarms_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_bill_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_chart_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_circuits_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_energy_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_home_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_voltage_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_wifi_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_wt3213_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/ui_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/ui.c)